travis:
  secure:
    BINSTAR_TOKEN: a5hV8KMC/yL+UXfYgSRfO35ibrSa7xTiGOGuTMelBG8U0y+gwc+wXy+l3q/g/q0gciWV5Qr50SSJ9QYLnFaCZ8YEjd1HYRDNXe8XNXsv09srG3+Mkyki53Z+JZEZu2qgkYZwE1fOlZZPOpOGzfvdueSBdJ3xxafWT1v1XYP4L8Wqpu7xOPpK0VKJEriB7+gustPGHibZhgOT2pJw9ioUAVrvO1nxHrxv+SrZrV0iG0C+Y0vxQNxEZ4SsPlLjqbU8ChhQZu4HjnCHUEBZ947xCYYDWRrxx3eah/Y2r1Kx8BUODpp0nweb3s3MtCt5eUphnCubV9rn6Bpy/I3q+GwLUgSxnodGs6qGbrkchVw3Gy1sojmKMMLCkC5m3U47553i9XNzJBMATSxfh2PXKuh5i1tuODGPSZk6M5zSxd5vfCUcet+Q6lxJg+dRfEWGhlQXhZCdcJhw1957jCPp5lT1CFWEn+2Awq2u7hs+ZRYoG4AR4JghY3L69usQHmJFseJK/D6TW++1sVzdpk4jKilgIZWF5pCQBJYiQaefvvG0ti0IPpr+D6gLuZjzyqSNkxACAmGfx6pexRw9bVGltdxlLJe8BR+hwu8KfpZGLaWVtqXpqfnmZqPImb/fsJKn7v33uxcsWsSDdMWs5N/4/Bca19SXbm0tpsIfy1VwPRxpXzg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
